AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  clientAppConnection

  Sample SAM Template for clientAppConnection

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: python3.8

Resources:
  ClientAppConnectionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: clientAppConnection/
      Handler: app.calculate_points
  

  ClientAppGetIdFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: clientAppConnection/
      Handler: app.get_external_client_id_mock_up


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ClientAppConnectionFunction:
    Description: "clientAppConnection Lambda Function ARN"
    Value: !GetAtt ClientAppConnectionFunction.Arn
  ClientAppConnectionFunctionIamRole:
    Description: "Implicit IAM Role created for clientAppConnection"
    Value: !GetAtt ClientAppConnectionFunctionRole.Arn
